version: '3.1'
services:
  assign_mongo:
    container_name: assign_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - assign_network

networks:
  assign_network: